year = int(input("Enter the year: "))
genre = input("Enter the genre: ")
album = input("Enter the album: ")
title = input("Enter the song title: ")
artist = input("Enter the artist: ")

print("--------------------------")
print("SONG DETAILS")
print("--------------------------")

print(f"Year Released: {year}")
print("Genre: %s" % genre)
print("Album: %s" % album)
print(f'Title: "{title}"')
print("Artist: " + artist)